services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: neatline
      MYSQL_USER: neatline
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mounts/database/data:/var/lib/mysql
  neatline:
    build: ./docker/neatline
    ports:
      - "8080:80"
    environment:
      - DB_HOST=database
      - DB_NAME=neatline
      - DB_USER=neatline
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mounts/neatline/database.ini:/var/www/html/config/database.ini
    depends_on:
      - database